//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SLControl.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SLCONTROL_DIALOG            102
#define IDR_HTML_LC_DOUT_TAB            104
#define IDR_MAINFRAME                   128
#define IDD_SL_SREC_Dialog              129
#define IDR_SLCONTROL_MENU              130
#define IDD_Calibration_Dialog          132
#define IDD_Calibration_Display         133
#define IDD_Experiment_display          134
#define IDB_BITMAP1                     141
#define IDD_FIT_DIALOG                  143
#define IDD_ken_test                    144
#define IDD_FIT_CONTROL                 145
#define IDD_ANALYSIS_DISPLAY            149
#define IDR_ANALYSIS_DISPLAY_MENU       151
#define IDD_SQUARE_WAVE_DIALOG          153
#define IDD_Scan_channels_dialog        154
#define IDD_SUPERPOSITION_DIALOG        155
#define IDD_SUPERPOSITION_CONTROL       156
#define IDR_SUPERPOSITION_MENU          157
#define IDD_TENSION_CONTROL             158
#define IDD_BATCH_ANALYSIS              168
#define IDC_CURSOR1                     171
#define IDD_CYCLICAL                    172
#define IDD_CHIRP                       174
#define IDD_FILE_HEADER                 177
#define IDD_TRIGGERS                    178
#define IDR_VERSION2                    178
#define ID_EXPERIMENTS_TRIGGERS         181
#define ID_SYSTEMCHECKS_SETMEMORYSTATE  182
#define ID_SYSTEMCHECKS_CHECKMEMORY183  183
#define IDD_CHANNEL_TAB                 185
#define ID_FILE_LOADEXPERIMENTPROTOCOL  187
#define ID_FILE_SAVEEXPERIMENTPROTOCOL  188
#define ID_HELP_CHECKFORUPDATE          189
#define IDI_ICON1                       191
#define IDD_CHECKING_FOR_UPDATES        192
#define ID_SYSTEMCHECKS_SETMEMSTATE193  193
#define IDD_LENGTH_CONTROL              193
#define ID_SYSTEMCHECKS_CHECKMEMSTATE   194
#define ID_SYSTEMCHECKS_CHECKMEMORY195  195
#define IDD_LC_GENERIC_PAGE             204
#define IDD_LC_FREEFORM_PAGE            206
#define IDD_LC_RAMP_PAGE                207
#define IDD_MULTIPLE_TRIALS_DIALOG      209
#define IDD_LC_TRIGGERED_PAGE           210
#define IDD_LC_DOUT_PAGE                211
#define IDD_LC_DOUT_TAB                 213
#define IDD_LC_KTR_STEP_PAGE            215
#define IDD_LC_SUMMARY_PAGE             217
#define IDC_Run_Experiment              1001
#define IDC_Abort                       1003
#define IDC_SL_to_FL_volts_calibration  1004
#define IDC_FL                          1005
#define IDC_SL_volts_to_FL_volts        1005
#define IDC_SL                          1006
#define IDC_SL_volts_to_FL_microns      1006
#define IDC_Calibration_Step            1007
#define IDC_SL_to_FL_Calibration_Override 1008
#define IDC_AREA                        1008
#define IDC_CALIBRATE                   1012
#define IDC_SL_CHANGE                   1013
#define IDC_FL_CHANGE                   1014
#define IDC_KTR_STEP_SIZE               1015
#define IDC_KTR_STEP_DURATION           1016
#define IDC_PRE_SERVO_POINTS            1017
#define IDC_PRE_SERVO                   1017
#define IDC_PROPORTIONAL_GAIN           1018
#define IDC_SERVO                       1018
#define IDC_POST_KTR                    1019
#define IDC_SERVO_MODE                  1020
#define IDC_TRIANGLE_SIZE               1020
#define IDC_CLAMP_MODE                  1021
#define IDC_SAMPLING_RATE               1022
#define IDC_DATA_POINTS                 1023
#define IDC_DURATION                    1024
#define IDC_ISOTONIC_LEVEL              1024
#define IDC_TRI_SIZE                    1025
#define IDC_GAIN                        1025
#define IDC_TRI_HALFTIME                1026
#define IDC_LENGTH_FUNCTION             1026
#define IDC_INTER_STRETCH_DELAY         1026
#define IDC_NO_OF_TRIANGLES             1027
#define IDC_CHIRP_SWEEP                 1027
#define IDC_HOLD_PERIOD                 1027
#define IDC_KTR_SLCONTROL_DURATION_MS   1028
#define IDC_INTEGRAL_GAIN               1028
#define IDC_DATA_PATH                   1029
#define IDC_DATA_BASE                   1030
#define IDC_DATA_INDEX                  1031
#define IDC_KTR_SL_CONTROL_DURATION     1032
#define IDC_PRE_KTR                     1032
#define IDC_PRE_TRI                     1033
#define IDC_POST_TRI                    1034
#define IDC_POST_KTR_FL                 1034
#define IDC_PERIOD                      1034
#define IDC_POST_KTR_FINAL_FL           1035
#define IDC_PRE_TENSION_SERVO           1035
#define IDC_LENGTH_DURATION             1036
#define IDC_PHASE                       1037
#define IDC_KTR_SLCONTROL               1038
#define IDC_BATCH_FILE                  1039
#define IDC_OFFSET                      1039
#define IDC_INTER_TRIAL_INTERVAL        1040
#define IDC_BEGIN_PERIOD                1040
#define IDC_INTER_TRIANGLE_INTERVAL     1041
#define IDC_INTER_PULL_INTERVAL         1041
#define IDC_MID_PERIOD                  1041
#define IDC_END_PERIOD                  1042
#define IDC_PLOT_LIST                   1051
#define IDC_FUNCTION_LIST               1052
#define IDC_FIT_BUTTON                  1053
#define IDC_p0                          1054
#define IDC_p1                          1055
#define IDC_START                       1055
#define IDC_p2                          1056
#define IDC_FL_STEP_SIZE                1056
#define IDC_p3                          1057
#define IDC_FL_STEP_DURATION            1057
#define IDC_FIT_FUNCTION                1058
#define IDC_STOP                        1058
#define IDC_FORCE_VALUE                 1058
#define IDC_R_SQUARED                   1059
#define IDC_SL_VALUE                    1059
#define IDC_FL_VALUE                    1061
#define IDC_SL_INT_VALUE                1062
#define IDC_TIME                        1063
#define IDC_EXPT_MODE                   1078
#define IDC_RAMP_CONTROL                1079
#define IDC_RAMP_INCREMENT_CONTROL      1080
#define IDC_PLOT_OTHER_TRACES           1082
#define IDC_ADJUST_FIRST_TRACE          1083
#define IDC_DURATION_CONTROL            1084
#define IDC_AVERAGE                     1084
#define IDC_SL_volts_to_FL_COMMAND_volts 1090
#define IDC_LIST_FILE                   1093
#define IDC_OUTPUT_FILE                 1094
#define IDC_ANALYSE                     1095
#define IDC_FIT_POINTS                  1096
#define IDC_X_FILTER                    1098
#define IDC_Y_FILTER                    1099
#define IDC_X_ROGUE_POINTS              1100
#define IDC_Y_ROGUE_POINTS              1101
#define IDC_ANALYSIS_MODE               1102
#define IDC_STRETCH_NUMBER              1107
#define IDC_SPIN_STRETCH_NUMBER         1108
#define IDC_KTR_SKIP_POINTS             1110
#define IDC_KTR_FUNCTION                1111
#define IDC_FV_PRE_KTR_POINTS           1111
#define IDC_AVERAGE_FILE_STRING         1112
#define IDC_ANALYSIS_OPTIONS            1118
#define IDC_EXPERIMENT_MODE             1119
#define IDC_LIST_FILE_BROWSE            1122
#define IDC_OUTPUT_FILE_BROWSE          1123
#define IDC_SL_to_FL_Calibration        1135
#define IDC_SL_to_FL_microns_calibration 1136
#define IDC_KTR_SLCONTROL_DURATION      1137
#define IDC_KTR_FL_SETTLE               1138
#define IDC_PRE_LENGTH                  1139
#define IDC_LENGTH_SIZE                 1140
#define IDC_MID_POSITION                1141
#define IDC_CALIBRATED_VALUES           1144
#define IDC_ALIGN                       1145
#define IDC_SHUFFLE_ORDER               1146
#define IDC_HEADER                      1147
#define IDC_TAB1                        1148
#define IDC_CHANNEL_TAB_CONTROL         1148
#define IDC_LC_DOUT_TAB_CONTROL         1148
#define IDC_KTR_INITIATION              1150
#define IDC_CHANNEL_ACTIVE              1154
#define IDC_ONE_SHOT                    1155
#define IDC_TRAIN                       1156
#define IDC_FREE_FORM                   1157
#define IDC_START_LEVEL                 1161
#define IDC_CHANNEL_SWITCH              1162
#define IDC_EDIT3                       1163
#define IDC_CHANNEL_DURATION            1163
#define IDC_LC_KTR_SIZE                 1163
#define IDC_PRE_FILE                    1163
#define IDC_BUTTON1                     1164
#define IDC_BROWSE_PATH                 1164
#define IDC_LC_PRE_KTR                  1164
#define IDC_LC_KTR_STEP_PAGE_BROWSE     1164
#define IDC_BROWSE                      1165
#define IDC_LC_KTR_DURATION             1165
#define IDC_EDIT4                       1166
#define IDC_GATE_ON                     1166
#define IDC_EMAIL                       1166
#define IDC_EDIT5                       1167
#define IDC_GATE_OFF                    1167
#define IDC_URL                         1167
#define IDC_RISE_FILE                   1167
#define IDC_EDIT6                       1168
#define IDC_FREQUENCY                   1168
#define IDC_STATIC2                     1168
#define IDC_RISE_BROWSE                 1168
#define IDC_EDIT7                       1169
#define IDC_DUTY_CYCLE                  1169
#define IDC_OK                          1169
#define IDC_EDIT8                       1173
#define IDC_FREE_FORM_FILE              1173
#define IDC_LC_SHEET_FRAME              1173
#define IDC_EDIT1                       1174
#define IDC_FREEFORM_LISTFILE           1174
#define IDC_LC_KTR_STEP_FILE            1174
#define IDC_FILE_INFO_BOX               1178
#define IDC_PATH_BROWSE                 1181
#define IDC_BUTTON3                     1183
#define IDC_FREEFORM_MODE               1184
#define IDC_LC_ABORT                    1185
#define IDC_LC_KTR_BATCH_MODE           1186
#define IDC_LC_BATCH_MODE_FILE          1187
#define IDC_PRE_MODE                    1192
#define IDC_PRE_VALUE                   1193
#define IDC_RISETIME                    1194
#define IDC_RAMP                        1195
#define IDC_NO_OF_STRETCHES             1196
#define IDC_RISE_MODE                   1197
#define IDC_STRETCH_SIZE                1198
#define IDC_PRE_RAMP_BROWSE             1199
#define IDC_PRE_BROWSE                  1199
#define IDC_TRIGGERED_CAPTURE           1200
#define IDC_HOLD                        1200
#define IDC_NO_OF_CHANNELS              1202
#define IDC_ANALOG_TRIGGER_CHANNEL      1203
#define IDC_ANALOG_THRESHOLD            1204
#define IDC_LC_DOUT_SHEET               1205
#define IDC_COMBO1                      1206
#define IDC_LC_KTR_STEP_PAGE_MODE       1207
#define IDC_KTR_STEP_PAGE_SIZE          1208
#define IDC_KTR_STEP_PAGE_DURATION      1209
#define IDC_KTR_STEP_PAGE_PRE           1210
#define IDC_SUMMARY_LIST_CONTROL        1210
#define IDC_LC_PARAMETER_UPDATE         7001
#define ID_FILE_EXIT                    32771
#define ID_HELP_ABOUT                   32772
#define ID_EXPERIMENTS_SLSREC           32773
#define ID_ANALYSIS_SINGLEDATAFILE      32775
#define ID_ANALYSIS_BATCHPROCESSING     32776
#define ID_HELP_CALIBRATIONPARAMETERS   32777
#define ID_ANALYSIS_KENTEST             32778
#define ID_SYSTEMCHECKS_SQUAREWAVEFL    32780
#define ID_SYSTEMCHECKS_READCHANNELS    32782
#define ID_TRANSFORM_CHANGETOCALIBRATEDVALUES 32783
#define ID_TRANSFORM_CHANGETORAWVOLTAGES 32784
#define ID_FILE_DUMPTRACEVALUESTOFILE   32785
#define ID_OFFSET_RESCALEFORCETOACTIVECURSOR 32786
#define ID_HELP_DOCUMENTATION           32788
#define ID_ANALYSIS_SUPERPOSITION       32789
#define ID_FILE_COPYTOCLIPBOARD         32790
#define ID_EXPERIMENTS_TENSIONCONTROL   32791
#define ID_HELP_VERSIONINFORMATION      32798
#define ID_ANALYSIS_BATCHANALYSIS       32808
#define ID_EXPERIMENTS_CYCLICAL         32811
#define ID_EXPERIMENTS_CHIRP            32813
#define ID_PEAK_POSITIONS               32814
#define ID_ANALYSIS_READDATAFILEHEADER  32818
#define ID_SYSTEMCHECKS_SETMEMSTATE     32821
#define ID_SYSTEMCHECKS_CHECKMEMORY     32822
#define ID_PEAK_RESETFILE               32824
#define ID_PEAK_ADDPOINT                32825
#define ID_EXPERIMENTS_LENGTH           32826

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        218
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1211
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
